  - name: Start mysql server
    shell: '{{ mysql_basedir }}/bin/mysqld_safe  --defaults-file={{ mysql_basedir }}/etc/my.cnf  --user={{ mysql_os_user }}  &'  
    ignore_errors: yes 
  - name: Copy primary node change master sql
    template: src=rep_change_primary.j2 dest=/tmp/rep_change_primary.sql
    run_once: true
    when: ansible_default_ipv4.address  == group_replication_bootstraper
  - name: exce primary node change master sql
    shell: 'sleep 60;{{ mysql_basedir }}/bin/mysql  -uroot  -p{{ mysql_root_passwd }} -S {{ mysql_datadir }}/tmp/mysql_{{mysql_port}}.sock < /tmp/rep_change_primary.sql'
    ignore_errors: yes
    run_once: true      
    when: ansible_default_ipv4.address == group_replication_bootstraper
  - name: Delete primary node change master sql
    file:
        path: '/tmp/rep_change_primary.sql' 
        state: absent
    run_once: true
    when: ansible_default_ipv4.address == group_replication_bootstraper 
  - name: Copy other node change master sql
    template: src=rep_change_other.j2 dest=/tmp/rep_change_other.sql
    when:  ansible_default_ipv4.address  != group_replication_bootstraper
  - name: exce other node change master sql
    shell: '{{ mysql_basedir }}/bin/mysql  -uroot  -p{{ mysql_root_passwd }} -S {{ mysql_datadir }}/tmp/mysql_{{mysql_port}}.sock < /tmp/rep_change_other.sql'
    ignore_errors: yes     
    when: ansible_default_ipv4.address != group_replication_bootstraper
  - name: Delete primary node change master sql
    file:
        path: '/tmp/rep_change_other.sql' 
        state: absent
    when: ansible_default_ipv4.address != group_replication_bootstraper 
  - name: get  node info
    shell: '{{ mysql_basedir }}/bin/mysql  -uroot  -p{{ mysql_root_passwd }} -S {{ mysql_datadir }}/tmp/mysql_{{mysql_port}}.sock -e "SELECT * FROM performance_schema.replication_group_members\G"'
    ignore_errors: yes 
    register: primary_status
    run_once: true
  - name: get  node info
    debug: msg="{{primary_status.stdout}}"
    run_once: true